# encoding: utf-8

# Project: Ecosytem-based Automated Range Mapping (EBAR)
# Credits: Randal Greene, Christine Terwissen
# © NatureServe Canada 2019 under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

# Program: PointsFieldMapping.py
# Field mapping dictionaries for point data sources


gbif_fields = {'quality_grade': None,
               'unique_id': 'gbifID',
               'uri': 'occurrenceID',
               'license': 'license',
               'scientific_name': 'species',
               'longitude': 'decimalLongitude',
               'latitude': 'decimalLatitude',
               'srs': 'geodeticDatum',
               'coordinates_obscured': None,
               'private_longitude': None,
               'private_latitude': None,
               'accuracy': 'coordinateUncertaintyInMeters',
               'private_accuracy': None,
               'year': 'year',
               'month': 'month',
               'day': 'day',
               'date': None,
               'basis_of_record': 'basisOfRecord',
               'individual_count': 'individualCount'}

ncc_gbif_fields = {'quality_grade': None,
                   'unique_id': 'gbifID',
                   'uri': 'occurrence',
                   'license': 'license',
                   'scientific_name': 'species',
                   'longitude': 'decimalLon',
                   'latitude': 'decimalLat',
                   'srs': None,
                   'coordinates_obscured': None,
                   'private_longitude': None,
                   'private_latitude': None,
                   'accuracy': 'coordinate',
                   'private_accuracy': None,
                   'year': 'year_',
                   'month': 'month_',
                   'day': 'day_',
                   'date': 'eventDate',
                   'basis_of_record': 'basisOfRec',
                   'individual_count': None}

vertnet_fields = {'quality_grade': None,
                  'unique_id': 'occurrenceid',
                  'uri': 'occurrenceid',
                  'license': 'license',
                  'scientific_name': 'name',
                  'longitude': 'longitude',
                  'latitude': 'latitude',
                  'srs': 'geodeticdatum',
                  'coordinates_obscured': None,
                  'private_longitude': None,
                  'private_latitude': None,
                  'accuracy': 'coordinateuncertaintyinmeters',
                  'private_accuracy': None,
                  'year': 'year',
                  'month': 'month',
                  'day': 'day',
                  'date': 'eventdate',
                  'basis_of_record': 'basisofrecord',
                  'individual_count': 'individualcount'}

ecoengine_fields = {'quality_grade': None,
                    'unique_id': 'key',
                    'uri': 'url',
                    'license': None,
                    'scientific_name': 'name',
                    'longitude': 'longitude',
                    'latitude': 'latitude',
                    'srs': None,
                    'coordinates_obscured': None,
                    'private_longitude': None,
                    'private_latitude': None,
                    'accuracy': 'coordinate_uncertainty_in_meters',
                    'private_accuracy': None,
                    'year': None,
                    'month': None,
                    'day': None,
                    'date': 'begin_date',
                    'basis_of_record': 'observation_type',
                    'individual_count': None}

inaturalist_fields = {'quality_grade': 'quality_grade',
                      'unique_id': 'id',
                      'uri': 'url',
                      'license': 'license',
                      'scientific_name': 'scientific_name',
                      'longitude': 'longitude',
                      'latitude': 'latitude',
                      'srs': None,
                      'coordinates_obscured': 'coordinates_obscured',
                      'private_longitude': 'private_longitude',
                      'private_latitude': 'private_latitude',
                      'accuracy': 'positional_accuracy',
                      'private_accuracy': 'private_positional_accuracy',
                      'year': None,
                      'month': None,
                      'day': None,
                      'date': 'observed_on',
                      'basis_of_record': None,
                      'individual_count': None}

bison_fields = {'quality_grade': None,
                'unique_id': 'occurrenceID',
                'uri': None,
                'license': 'license',
                'scientific_name': 'name',
                'longitude': 'longitude',
                'latitude': 'latitude',
                'srs': None,
                'coordinates_obscured': None,
                'private_longitude': None,
                'private_latitude': None,
                'accuracy': None,
                'private_accuracy': None,
                'year': 'year',
                'month': None,
                'day': None,
                'date': 'date',
                'basis_of_record': 'basisOfRecord',
                'individual_count': None}

canadensys_fields = {'quality_grade': None,
                     'unique_id': 'occurrenceID',
                     'uri': None,
                     'license': 'dcterms:license',
                     'scientific_name': 'species',
                     'longitude': 'decimalLongitude',
                     'latitude': 'decimalLatitude',
                     'srs': 'verbatimCoordinateSystem',
                     'coordinates_obscured': None,
                     'private_longitude': None,
                     'private_latitude': None,
                     'accuracy': 'coordinateUncertaintyInMeters',
                     'private_accuracy': None,
                     'year': 'year',
                     'month': 'month',
                     'day': None,
                     'date': 'eventDate',
                     'basis_of_record': 'basisOfRecord',
                     'individual_count': 'individualCount'}

ncc_endemics_fields = {'quality_grade': None,
                       'unique_id': 'OBSERVATIO',
                       'uri': None,
                       'license': None,
                       'scientific_name': 'SCIENTIFIC',
                       'longitude': 'longitude',
                       'latitude': 'latitude',
                       'srs': None,
                       'coordinates_obscured': None,
                       'private_longitude': None,
                       'private_latitude': None,
                       'accuracy': None,
                       'private_accuracy': None,
                       'year': 'OBSERVAT_3',
                       'month': None,
                       'day': None,
                       'date': 'OBSERVAT_2',
                       'basis_of_record': None,
                       'individual_count': None}

idigbio_fields = {'quality_grade': None,
                  'unique_id': 'etag',
                  'uri': None,
                  'license': None,
                  'scientific_name': 'name',
                  'longitude': 'longitude',
                  'latitude': 'latitude',
                  'srs': None,
                  'coordinates_obscured': None,
                  'private_longitude': None,
                  'private_latitude': None,
                  'accuracy': None,
                  'private_accuracy': None,
                  'year': None,
                  'month': None,
                  'day': None,
                  'date': 'datecollected',
                  'basis_of_record': 'basisofrecord',
                  'individual_count': 'individualcount'}

other_fields = {'quality_grade': None,
                'unique_id': 'originalID',
                'uri': None,
                'license': None,
                'scientific_name': 'speciesName',
                'longitude': 'longitude',
                'latitude': 'latitude',
                'srs': 'datum',
                'coordinates_obscured': None,
                'private_longitude': None,
                'private_latitude': None,
                'accuracy': 'uncertaintyDistance',
                'private_accuracy': None,
                'year': 'Year',
                'month': 'Month',
                'day': 'Day',
                'date': 'observationDate',
                'basis_of_record': None,
                'individual_count': 'individualsCount'}
